# This workflow will install Python dependencies and run some static tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python dependencies
        run: |
          python -m pip install mypy -r requirements.txt
      - name: Mypy
        uses: liskin/gh-problem-matcher-wrap@v3
        with:
          linters: mypy
          run: mypy --show-column-numbers .
